import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';

export default function Home() {
  const CLIENT_ID = "cc92025849f240619dcb824dc6f637ba";
  const REDIRECT_URI = "http://localhost:3000";
  const AUTH_ENDPOINT = "https://accounts.spotify.com/authorize";
  const RESPONSE_TYPE = "token";

  const [token, setToken] = useState("");

  useEffect(()=> {
    const hash = window.location.hash;
    let token = window.localStorage.getItem('token');

    if(!token && hash){
      token = hash.substring(1).split("&").find(elem => elem.startsWith("access_token")).split("-")[1];

      console.log(token)
      window.location.hash = "";
      window.localStorage.setItem('token', token);

      setToken(token);
    }

  },[]);

  const logOut = () => {
    setToken('');
    window.localStorage.removeItem('token');
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Playlist App</h1>

        {!token ? (
          <a href={`${AUTH_ENDPOINT}?client_id=${CLIENT_ID}&redirect_uri=${REDIRECT_URI}&response_type=${RESPONSE_TYPE}`}>Login with spotify</a>
        ): (
          <button onClick={(e) => {logOut()}}>log out</button>
        )}
        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
